<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class LombaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('lombas')->insert([
            [
                'judul' => 'Web Development',
                'kategori' => 'Akademik',
                'deskripsi' => 'Lomba Web Development untuk mahasiswa se-Indonesia.',
                'penyelenggara' => 'Universitas Muhammadiyah Riau',
                'link_registrasi' => 'https://linktr.ee/nifc4.0',
                'awal_registrasi' => Carbon::parse('2023-09-01'),
                'akhir_registrasi' => Carbon::parse('2023-10-01'),
                'tingkatan_lomba_id' => 1,
                'bidang_keahlian_id' => 1,
                'minat_id' => 1,
                'created_by' => 1,
                'status_verifikasi' => 'verified',
                'jenis_pendaftaran' => 'berbayar', 
                'harga_pendaftaran' => 50000,
                'perkiraan_hadiah' =>5000000,
                'mendapatkan_uang' => true,
                'mendapatkan_sertifikat' => true,
                'nilai_benefit' => 80,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // [
            //     'judul' => 'Hackathon Inovasi Teknologi 2024',
            //     'kategori' => 'Non Akademik',
            //     'deskripsi' => 'Ajang pengembangan solusi teknologi inovatif dalam 48 jam.',
            //     'penyelenggara' => 'Tech Innovators Community',
            //     'link_registrasi' => 'http://hackathon.example.com/register',
            //     'awal_registrasi' => Carbon::parse('2024-01-10'),
            //     'akhir_registrasi' => Carbon::parse('2024-02-10'),
            //     'tingkatan_lomba_id' => 1,
            //     'bidang_keahlian_id' => 2,
            //     'minat_id' => 2,
            //     'created_by' => 1,
            //     'status_verifikasi' => 'approved',
            //     'jenis_pendaftaran' => 'gratis', 
            //     'harga_pendaftaran' => 0,
            //     'perkiraan_hadiah' => 'Kesempatan magang di startup dan hadiah menarik',
            //     'mendapatkan_uang' => false,
            //     'mendapatkan_sertifikat' => true,
            //     'nilai_benefit' => 90,
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'judul' => 'Lomba Debat Bahasa Inggris Mahasiswa',
            //     'kategori' => 'Akademik',
            //     'deskripsi' => 'Kompetisi debat untuk mengasah kemampuan berbahasa Inggris dan berpikir kritis.',
            //     'penyelenggara' => 'Universitas Global',
            //     'link_registrasi' => 'http://debat.example.com/daftar',
            //     'awal_registrasi' => Carbon::parse('2023-11-01'),
            //     'akhir_registrasi' => Carbon::parse('2023-12-01'),
            //     'tingkatan_lomba_id' => 2,
            //     'bidang_keahlian_id' => 3,
            //     'minat_id' => 3,
            //     'created_by' => 1,
            //     'status_verifikasi' => 'pending',
            //     'jenis_pendaftaran' => 'berbayar', 
            //     'harga_pendaftaran' => 75000,
            //     'perkiraan_hadiah' => 'Beasiswa pendidikan dan sertifikat',
            //     'mendapatkan_uang' => false,
            //     'mendapatkan_sertifikat' => true,
            //     'nilai_benefit' => 75,
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            
            // [
            //     'judul' => 'Kompetisi Pemrograman Nasional (Kopertinas)',
            //     'kategori' => 'Akademik',
            //     'deskripsi' => 'Kompetisi coding tahunan untuk mahasiswa informatika.',
            //     'penyelenggara' => 'Asosiasi Ilmu Komputer Indonesia',
            //     'link_registrasi' => 'http://kopertinas.example.com/daftar',
            //     'awal_registrasi' => Carbon::parse('2024-03-01'),
            //     'akhir_registrasi' => Carbon::parse('2024-04-01'),
            //     'tingkatan_lomba_id' => 1,
            //     'bidang_keahlian_id' => 2,
            //     'minat_id' => 2,
            //     'created_by' => 1,
            //     'status_verifikasi' => 'approved',
            //     'jenis_pendaftaran' => 'berbayar', 
            //     'harga_pendaftaran' => 100000,
            //     'perkiraan_hadiah' => 'Uang tunai Rp 10.000.000, beasiswa, dan kesempatan magang',
            //     'mendapatkan_uang' => true,
            //     'mendapatkan_sertifikat' => true,
            //     'nilai_benefit' => 95,
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'judul' => 'Lomba Desain UI/UX Aplikasi Mobile',
            //     'kategori' => 'Non Akademik',
            //     'deskripsi' => 'Mendesain antarmuka pengguna yang intuitif dan menarik untuk aplikasi mobile.',
            //     'penyelenggara' => 'Komunitas Desainer Digital',
            //     'link_registrasi' => 'http://uiux-design.example.com/apply',
            //     'awal_registrasi' => Carbon::parse('2024-04-15'),
            //     'akhir_registrasi' => Carbon::parse('2024-05-15'),
            //     'tingkatan_lomba_id' => 2,
            //     'bidang_keahlian_id' => 2,
            //     'minat_id' => 4,
            //     'created_by' => 1,
            //     'status_verifikasi' => 'approved',
            //     'jenis_pendaftaran' => 'gratis', 
            //     'harga_pendaftaran' => 0,
            //     'perkiraan_hadiah' => 'Tablet grafis, langganan software desain, dan sertifikat',
            //     'mendapatkan_uang' => false,
            //     'mendapatkan_sertifikat' => true,
            //     'nilai_benefit' => 85,
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'judul' => 'Kompetisi Data Science & Machine Learning',
            //     'kategori' => 'Akademik',
            //     'deskripsi' => 'Analisis data dan pengembangan model machine learning untuk memecahkan masalah nyata.',
            //     'penyelenggara' => 'Pusat Riset Data Nasional',
            //     'link_registrasi' => 'http://datasciencecomp.example.com/join',
            //     'awal_registrasi' => Carbon::parse('2024-05-01'),
            //     'akhir_registrasi' => Carbon::parse('2024-06-01'),
            //     'tingkatan_lomba_id' => 1,
            //     'bidang_keahlian_id' => 2,
            //     'minat_id' => 5,
            //     'created_by' => 1,
            //     'status_verifikasi' => 'pending',
            //     'jenis_pendaftaran' => 'berbayar',
            //     'harga_pendaftaran' => 150000,
            //     'perkiraan_hadiah' => 'Uang tunai Rp 7.500.000 dan kesempatan publikasi ilmiah',
            //     'mendapatkan_uang' => true,
            //     'mendapatkan_sertifikat' => true,
            //     'nilai_benefit' => 92,
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'judul' => 'Web Development Challenge 2024',
            //     'kategori' => 'Non Akademik',
            //     'deskripsi' => 'Membangun aplikasi web fungsional dalam waktu terbatas.',
            //     'penyelenggara' => 'Developer Community Indonesia',
            //     'link_registrasi' => 'http://webdevchallenge.example.com/register',
            //     'awal_registrasi' => Carbon::parse('2024-06-10'),
            //     'akhir_registrasi' => Carbon::parse('2024-07-10'),
            //     'tingkatan_lomba_id' => 2,
            //     'bidang_keahlian_id' => 2,
            //     'minat_id' => 2,
            //     'created_by' => 1,
            //     'status_verifikasi' => 'approved',
            //     'jenis_pendaftaran' => 'berbayar',
            //     'harga_pendaftaran' => 25000,
            //     'perkiraan_hadiah' => 'Lisensi software premium dan voucher kursus online',
            //     'mendapatkan_uang' => false,
            //     'mendapatkan_sertifikat' => true,
            //     'nilai_benefit' => 88,
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'judul' => 'Competitive Programming League (CPL)',
            //     'kategori' => 'Akademik',
            //     'deskripsi' => 'Liga pemrograman kompetitif bulanan untuk mengasah kemampuan algoritma.',
            //     'penyelenggara' => 'ProCode Community',
            //     'link_registrasi' => 'http://cpl.example.com/join',
            //     'awal_registrasi' => Carbon::parse('2024-08-01'),
            //     'akhir_registrasi' => Carbon::parse('2024-08-10'),
            //     'tingkatan_lomba_id' => 3,
            //     'bidang_keahlian_id' => 2,
            //     'minat_id' => 2,
            //     'created_by' => 1,
            //     'status_verifikasi' => 'approved',
            //     'jenis_pendaftaran' => 'gratis', 
            //     'harga_pendaftaran' => 0,
            //     'perkiraan_hadiah' => 'Poin peringkat, merchandise, dan sertifikat',
            //     'mendapatkan_uang' => false,
            //     'mendapatkan_sertifikat' => true,
            //     'nilai_benefit' => 80,
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'judul' => 'Mobile App Innovation Challenge',
            //     'kategori' => 'Non Akademik',
            //     'deskripsi' => 'Tantangan menciptakan aplikasi mobile inovatif untuk solusi masalah sosial.',
            //     'penyelenggara' => 'Startup Incubator X',
            //     'link_registrasi' => 'http://mobileappchallenge.example.com/register',
            //     'awal_registrasi' => Carbon::parse('2024-09-01'),
            //     'akhir_registrasi' => Carbon::parse('2024-10-01'),
            //     'tingkatan_lomba_id' => 1,
            //     'bidang_keahlian_id' => 2,
            //     'minat_id' => 2,
            //     'created_by' => 1,
            //     'status_verifikasi' => 'pending',
            //     'jenis_pendaftaran' => 'gratis', 
            //     'harga_pendaftaran' => 0,
            //     'perkiraan_hadiah' => 'Pendanaan startup, mentoring, dan sertifikat',
            //     'mendapatkan_uang' => true,
            //     'mendapatkan_sertifikat' => true,
            //     'nilai_benefit' => 98,
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'judul' => 'Cyber Security Capture The Flag (CTF)',
            //     'kategori' => 'Non Akademik',
            //     'deskripsi' => 'Kompetisi keamanan siber untuk menguji kemampuan hacking etis dan pertahanan.',
            //     'penyelenggara' => 'CyberSec Community ID',
            //     'link_registrasi' => 'http://ctf.example.com/enroll',
            //     'awal_registrasi' => Carbon::parse('2024-10-01'),
            //     'akhir_registrasi' => Carbon::parse('2024-10-20'),
            //     'tingkatan_lomba_id' => 2,
            //     'bidang_keahlian_id' => 2,
            //     'minat_id' => 6,
            //     'created_by' => 1,
            //     'status_verifikasi' => 'approved',
            //     'jenis_pendaftaran' => 'gratis', 
            //     'harga_pendaftaran' => 0,
            //     'perkiraan_hadiah' => 'Perangkat keamanan, voucher kursus, dan sertifikat',
            //     'mendapatkan_uang' => false,
            //     'mendapatkan_sertifikat' => true,
            //     'nilai_benefit' => 90,
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
            // [
            //     'judul' => 'Artificial Intelligence Challenge (AIC)',
            //     'kategori' => 'Akademik',
            //     'deskripsi' => 'Mengembangkan solusi AI untuk masalah dunia nyata.',
            //     'penyelenggara' => 'Pusat Riset AI Nasional',
            //     'link_registrasi' => 'http://aichallenge.example.com/apply',
            //     'awal_registrasi' => Carbon::parse('2024-11-01'),
            //     'akhir_registrasi' => Carbon::parse('2024-12-01'),
            //     'tingkatan_lomba_id' => 1,
            //     'bidang_keahlian_id' => 2,
            //     'minat_id' => 5,
            //     'created_by' => 1,
            //     'status_verifikasi' => 'approved',
            //     'jenis_pendaftaran' => 'berbayar', 
            //     'harga_pendaftaran' => 200000,
            //     'perkiraan_hadiah' => 'Uang tunai Rp 15.000.000 dan kesempatan publikasi',
            //     'mendapatkan_uang' => true,
            //     'mendapatkan_sertifikat' => true,
            //     'nilai_benefit' => 99,
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            // ],
        ]);
    }
}